-- CreateEnum
CREATE TYPE "ReviewMode" AS ENUM ('SUBMISSION_READINESS', 'DOCUMENTATION_REVIEW', 'CONSTRUCTABILITY_REVIEW', 'COORDINATION_REVIEW', 'COMPLIANCE_RISK_REVIEW');

-- AlterTable
ALTER TABLE "analyses" ADD COLUMN     "reviewMode" "ReviewMode" NOT NULL DEFAULT 'SUBMISSION_READINESS';
